name: Build and deploy WAR app to Azure Web App - KranthiWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -f MyWebApp/pom.xml  # Adjusted to ensure correct path

      - name: Check for target files
        run: ls -al MyWebApp/target  # Ensure this reflects the correct path

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: MyWebApp
          path: 'MyWebApp/target/*.war'  # Use .war as output is set to WAR in pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: MyWebApp
      
      - name: Debug Secrets
        run: |
          echo "Client ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}"
          echo "Tenant ID: ${{ secrets.AZUREAPPSERVICE_TENANTID }}"
          echo "Subscription ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZUREAPPSERVICE_CLIENTID }}","clientSecret":"${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}","tenantId":"${{ secrets.AZUREAPPSERVICE_TENANTID }}","subscriptionId":"${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}"}'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: KranthiWebApp  # Your Azure Web App name
          package: '*.war'  # Ensure this matches the artifact being deployed
