name: Build and Deploy WAR App to Azure Web App - KranthiWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: List directory contents for debugging
        run: ls -R kranthiWebApp  # List all files and directories under kranthiWebApp

      - name: Build with Maven
        run: mvn clean package -f kranthiWebApp/MyWebApp/pom.xml  # Build and package the WAR file

      - name: Check for target files
        run: ls -al kranthiWebApp/MyWebApp/target  # List target directory contents to see if WAR file is present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: MyWebApp
          path: 'kranthiWebApp/MyWebApp/target/*.war'  # Ensure the path to the WAR file is correct

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: MyWebApp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
