name: CI/CD Pipeline for MyWebApp

on:
  push:
    branches:
      - main  # Adjust this to your default branch if it's different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the version of Java your project requires
          distribution: 'temurin'  # You can also use 'adopt' or other distributions if needed

      - name: List files in MyWebApp directory
        run: ls -R kranthiWebApp/MyWebApp  # To verify the path

      - name: Build with Maven
        run: mvn clean install -f kranthiWebApp/MyWebApp/pom.xml

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyWebApp
          path: kranthiWebApp/MyWebApp/target/MyWebApp.war  # Update this path if the WAR file name is different
